const routesPath = {
  REMEMBERUSER: 'rememberUser',
  TOKEN: 'token',
  LOGIN: '/',
  LOGOUT: '/logout',
  SIGNUP: '/signup',
  PASSWORDRESET: '/password/reset',
  DASHBOARD: '/dashboard',
  TRANSACTIONINFORMATION: '/transactioninformation',
  KYC: '/kyc',
  SUPPORT: '/support',
  SETTLEMENTS: '/settlements',
  RECONCILIATION: '/reconciliation',
  RECONCILIATIONUSERDETAILS: '/reconciliation/',
  USERS: '/users',
  SETTINGS: '/settings',
  KYCDOC: '/kyc/',
  USERDETAILS: '/user/profile/',
  TRANSACTIONS: '/transactions',
  NEWAPPNOTIFICATION: '/settings/newappnotification',
  EMAILNOTIFICATION: '/settings/emailnotification',
  NEWARTICLE: '/settings/newarticle',
};

export default routesPath;
